title:              IEEE IIST
email:              abhishekpythons@gmail.com
description:        A Website for IEE IIST
author:             Start Bootstrap
baseurl:            "/ieee-iist"
url:                "https://abhishekpythons.github.io"

# Social Profiles
twitter_username:   IEEE
github_username:    abhishekpythons
facebook_username:  None
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
